name: CI/CD Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Teste flake8 manualmente
        run: flake8 --version
      
      - name: Rodar testes
        run: pytest teste_CI_CD/test_main.py

      - name: Simulação de Deploy
        run: echo "Deploy realizado com sucesso!"
